### ISSUE TITLE
A log1.txt is being created when running testthat

### ISSUE THREAD

**Issue by stitam** [koralgooll/MulEA#14]
When I run test the following file is being created: `tests/testthat/log1.txt`

I think this may be coming from C++? My problem is the CRAN is quite strict on writing files to the file system:

"_Packages should not write in the user’s home filespace (including clipboards), nor anywhere else on the file system apart from the R session’s temporary directory (or during installation in the location pointed to by TMPDIR: and such usage should be cleaned up). Installing into the system’s R installation (e.g., scripts to its bin directory) is not allowed._ " (https://cran.r-project.org/web/packages/policies.html).

I am unsure what exactly is creating this file but if it is not essential and it is simple to eliminate it, I think we should.

Alternatively the files could be diverted to `tempdir()`

**Comment by koralgooll** [comment]
Hi Thomas, it is file for multithreading calculations logs. As we had an issues with this, now it is not necessary. I will change the log directory or remove it at all, then close the issue.

**Comment by koralgooll** [comment]
Issue is fixed, log file if any can be found in current tmp dir.
