### ISSUE TITLE
Fix R CMD check

### ISSUE THREAD

**Issue by stitam** [koralgooll/MulEA#18]
R CMD check sill produces warnings and notes. These should also be fixed before submission.

**Comment by stitam** [comment]
There is an issue I am unsure how to resolve: In `Plotting.R/plot_graph()` the term `geom_edge_arc(aes(width = weight), alpha = 0.5)` contains the argument `weight` which seems to be undefined. Any suggestions?

**Comment by stitam** [comment]
Solved, apparently if we use this construct, we have to be more specific on defining the environment, so in this case the solution is `geom_edge_arc(aes(width = .data$weight)`. Only in this case we also have to define `@importFrom rlang .data`. https://www.r-bloggers.com/2019/08/no-visible-binding-for-global-variable/

**Comment by koralgooll** [comment]
I have removed my issues presented after increasing test coverage and clearing package from unused and obsolated functions. Result of CHECK:

❯ checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    'README.Rmd'

0 errors ✔ | 0 warnings ✔ | 1 note ✖

**Comment by koralgooll** [comment]
@stitam could you try with your build ignore solution? :)

**Comment by koralgooll** [comment]
I have performed R CMD check with --as-cran flag on Ubuntu. Below are results:

── R CMD check results ──────────────────────────MulEA 0.99.10 ────
Duration: 1m 22.3s
0 errors ✔ | 0 warnings ✔ | 0 notes ✔
R CMD check succeeded

I will perform same on Windows. This flag is suggested as we have intention to push to CRAN. :)

**Comment by cmujzbit** [comment]
Result of R CMD check --as-cran:

── R CMD check results ─────────────────────────────── MulEA 0.99.10 ────
Duration: 2m 20.8s
0 errors ✔ | 0 warnings ✔ | 0 notes ✔
R CMD check succeeded

**Comment by cmujzbit** [comment]
I think we are ready to submit. :)
