### ISSUE TITLE
Upgrade to testthat 3 and increase coverage above 75%

### ISSUE THREAD

**Issue by stitam** [koralgooll/MulEA#19]

**Comment by koralgooll** [comment]
After update we have identify some tests issues. Probably connected with this:
> MulEA::gsea
Error: 'gsea' is not an exported object from 'namespace:MulEA'
So as you can see the gsea object is not exported properly. I am trying to fix it.

**Comment by koralgooll** [comment]
export(gsea) in NAMESPACE instead of exportClasses(gsea) will force the proper working. Still not fixed.

**Comment by koralgooll** [comment]
Testthat 3 is in place, all tests warning removed. NAMESPACE is properly generated, it exports ora and gsea classes.
Current coverage is presented.
> library(covr)
Warning message:
package ‘covr’ was built under R version 4.2.1 
> package_coverage()
MulEA Coverage: 34.69%
R/HypergeometricTest.R: 0.00%
R/MuleaData.R: 0.00%
R/Plotting.R: 0.00%
R/Zzz.R: 0.00%
R/Utils.R: 7.71%
R/Methods.R: 18.11%
src/set-based-enrichment-test.cpp: 79.71%
R/ORA.R: 80.56%
R/set-based-enrichment-test.r: 87.07%
R/GenericFunctions.R: 100.00%
R/RankedBasedTest.R: 100.00%
R/SetBasedEnrichmentTest.R: 100.00%
R/SubramanianTest.R: 100.00%

**Comment by koralgooll** [comment]
@stitam is any requirement for coverage for release? 👓

**Comment by stitam** [comment]
rOpenSci suggests 75% coverage (https://devguide.ropensci.org/building.html) to cover key functionality, but it seems CRAN does not require a specific test coverage. Maybe covering all examples, tests, readme and vignette would be a good compromise?

**Comment by koralgooll** [comment]
I have increased test coverage for core functions, I think it is much than better. I am closing this issue. 😄 
> package_coverage()
MulEA Coverage: 49.01%
R/Plotting.R: 0.00%
R/Utils.R: 27.49%
src/set-based-enrichment-test.cpp: 79.71%
R/ORA.R: 80.82%
R/set-based-enrichment-test.r: 84.87%
R/Methods.R: 85.71%
R/GenericFunctions.R: 100.00%
R/HypergeometricTest.R: 100.00%
R/RankedBasedTest.R: 100.00%
R/SetBasedEnrichmentTest.R: 100.00%
R/SubramanianTest.R: 100.00%
R/Zzz.R: 100.00%
