### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by stitam** [koralgooll/MulEA#4]
Hi, when I run the tests 12/17 fails, the main error message I receive is:
`Error in checkForRemoteErrors(lapply(cl, recvResult)) : 4 nodes produced errors; first error: there is no package called ‘MulEA’`

I found that this error message is produced by line 127 of testHypergeometricTest.R:
`muleaHypergeometricTestRes <- runTest(muleaHypergeometricTest)`

My assumption is that somewhere in the package there is a `library(MulEA)` and this causes the error. I only found this in `set-based-enrichment-test.r`: `clusterEvalQ(cl, library(MulEA))`. I removed this line and the error message changed. Now the problem I think is that in set-based-enrichment-test.r a function called `enrichment_test_simulation()` is called, however, it seems it is not defined. Do you have any suggestions what might be the simplest solution here?

Related to this issue, I noticed another script with a very similar name: `SetBasedEnrichmentTest.R` and I found that this function actually uses `set.based.enrichment.test()` in lines 106 and 132. Are these duplicatesor is this a C++ thing maybe? Is it correct that one uses the other?

Thanks,

**Comment by koralgooll** [comment]
Hi @stitam, I will resolve all tests problems as it were not updated properly in for last time. I will need more or less up to two weeks. I will try to deliver earlier, but can not give a guarantee for earlier. :)

**Comment by koralgooll** [comment]
I will cole the issue when tests problems solved.

**Comment by stitam** [comment]
Thanks @koralgooll, then I will limit my first PR to style updates and only move to more tests once the existing ones are fixed. Although it is not a requirement for the CRAN submission, it will probably save us a lot of time with future issues if we push our test coverage above 75%. If you can fix the existing tests, I can add in new ones afterwards.

**Comment by koralgooll** [comment]
Hi @stitam! Tests are fixed. Please check it, as I haven't any of presented by you problem. 
Please remember to pull are code from repository, like stash your changes then run tests to check if it has same behavior on your computer. It looks like some of your errors are result of multithread processing. I hope that last fix to that solve the issues. Let me know what is the status. :)

**Comment by stitam** [comment]
I found the source of my error, the package was not installed on my computer. On one hand, I installed the package so problem solved, on the other hand, I am not sure if it is good practice to include tests that depend on an _earlier_ version of the software: even if I reinstall the package after every change to the repo, after I do edits my local dev version will be different from the installed one which may lead to errors. This is probably because the package calls `library(MulEA)` at various locations. Do you think these could be eliminated?
