### ISSUE TITLE
Do we meet CRAN C++ guidelines?

### ISSUE THREAD

**Issue by stitam** [koralgooll/MulEA#7]
Here is a link to CRAN policies: https://cran.r-project.org/web/packages/policies.html

I don't have experience with C++ so I thought it's quicker to ask: do you think the package meets this requirement?

"(Using external C/C++/Fortran libraries.) Where a package wishes to make use of a library not written solely for the package, the package installation should first look to see if it is already installed and if so is of a suitable version. In case not, it is desirable to include the library sources in the package and compile them as part of package installation. If the sources are too large, it is acceptable to download them as part of installation, but do ensure that the download is of a fixed version rather than the latest. Only as a last resort and with the agreement of the CRAN team should a package download pre-compiled software.

On Windows and macOS static libraries must be used. A separate document, [External Libraries for CRAN packages](https://cran.r-project.org/web/packages/external_libs.html), covers what external libraries are or could be made available."

**Comment by koralgooll** [comment]
I think we use all standard libraries. Our code is build from code which is included here: https://github.com/koralgooll/MulEA/blob/master/src/set-based-enrichment-test.cpp.
In my opinion it is OK with requirements. If I am wrong please deliver more extensive problem's description. I will fix.
